name: OnlineList
description: Display online players sorted by server
author: StarTux
version: 0.1
main: com.winthier.onlinelist.OnlineListPlugin
depend: [Connect]
softdepend: [Vault]
commands:
  list:
    aliases: [ who, online, ls ]
    description: Display the player list
    permission: onlinelist.list
permissions:
  onlinelist.list:
    description: View the online list
    default: op
  onlinelist.reload:
    description: Reload the plugin
    default: op
  onlinelist.staff:
    description: Show up as staff
    default: op
